language: cpp
sudo: false
notifications:
  email: true

# Use Linux unless specified otherwise
os: linux
dist: trusty
ruby: 2.3

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    # GCC on Linux
    - os: linux
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && BUILD_TYPE=Debug"

    - os: linux
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && BUILD_TYPE=Release"

    - os: linux
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && BUILD_TYPE=Debug"

    - os: linux
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && BUILD_TYPE=Release"

    - os: linux
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && BUILD_TYPE=Debug"

    - os: linux
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && BUILD_TYPE=Release"

    # Clang on Linux
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - g++-5
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0 && BUILD_TYPE=Debug"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - g++-5
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0 && BUILD_TYPE=Release"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - g++-5
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && BUILD_TYPE=Debug"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - g++-5
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && BUILD_TYPE=Release"

    # Clang on OSX
    - os: osx
      osx_image: xcode8
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && BUILD_TYPE=Debug"

    - os: osx
      osx_image: xcode8
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && BUILD_TYPE=Release"

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && BUILD_TYPE=Debug"

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && BUILD_TYPE=Release"

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && BUILD_TYPE=Debug"

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && BUILD_TYPE=Release"

    - os: osx
      osx_image: xcode10
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && BUILD_TYPE=Debug"

    - os: osx
      osx_image: xcode10
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && BUILD_TYPE=Release"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"

  # Travis machines have 2 cores
  - JOBS=2

  # Have CMake to generate build files
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  
script:
  # Build and run tests
  - cmake --build . --config $BUILD_TYPE -- -j${JOBS}
  - ctest -C $BUILD_TYPE --output-on-failure -j${JOBS}

